[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2="1.0.24"
anyhow="1.0.58"
clap={version = "3.2.13", features = ["derive"]}
indicatif="0.16.2"
